# Generated by Django 3.2.6 on 2022-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('datefound', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=2000)),
                ('evid', models.IntegerField(default=0, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelevantLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=2000)),
                ('locid', models.IntegerField(default=0, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=2000)),
                ('age', models.IntegerField(default=18)),
                ('guilty', models.BooleanField(default=False)),
                ('susid', models.IntegerField(default=0, verbose_name='ID')),
                ('evidence', models.ManyToManyField(to='MetaApp.EvidenceModel')),
                ('locations', models.ManyToManyField(to='MetaApp.RelevantLocationModel')),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('target', models.CharField(choices=[('Individual', 'Individual'), ('School', 'School'), ('Public Building', 'Public Building'), ('Crypto Exchange', 'Crypto Exchange'), ('Online Gaming Platform', 'Online Gaming Platform'), ('Corporation', 'Corporation'), ('Online Forum', 'Online Forum'), ('Other', 'Other')], max_length=100)),
                ('description', models.CharField(default='N/A', max_length=2000)),
                ('mainlink', models.CharField(default='N/A', max_length=2000)),
                ('targetother', models.CharField(default='N/A', max_length=200)),
                ('author', models.CharField(default='Superuser', max_length=200)),
                ('closed', models.BooleanField(default=False)),
                ('cryptoamount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('reportid', models.IntegerField(default=0, verbose_name='ID')),
                ('readabletech', models.CharField(max_length=1000)),
                ('evidence', models.ManyToManyField(to='MetaApp.EvidenceModel')),
                ('relevantlocations', models.ManyToManyField(to='MetaApp.RelevantLocationModel')),
                ('suspects', models.ManyToManyField(to='MetaApp.SuspectModel')),
                ('techinvolved', models.ManyToManyField(to='MetaApp.InvolvedTech')),
            ],
        ),
    ]
