# Generated by Django 3.2.6 on 2022-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('crime_category', models.TextField(choices=[('AS', 'Assault'), ('SV', 'Sexual Violence')], default='Assault')),
            ],
        ),
    ]
