# Generated by Django 3.2.6 on 2022-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='crime_category',
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='crimecategory',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='description',
            field=models.CharField(default='N/A', max_length=2000),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='govreport',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='medialinks',
            field=models.CharField(default='N/A', max_length=2000),
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='platform',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
