# Generated by Django 3.2.6 on 2022-06-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0002_auto_20220613_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='time',
            field=models.CharField(max_length=300),
        ),
    ]
