# Generated by Django 3.2.6 on 2022-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0003_auto_20220613_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='crimecategory',
            field=models.CharField(choices=[('AS', 'Assault'), ('SV', 'Sexual Violence')], max_length=100, verbose_name='Crime Category'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
