# Generated by Django 3.2.6 on 2022-06-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0005_auto_20220620_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='target',
            field=models.CharField(choices=[('I', 'Individual'), ('S', 'School'), ('PB', 'Public Building'), ('O', 'Other')], max_length=100),
        ),
    ]
