# Generated by Django 3.2.6 on 2022-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0006_alter_reportmodel_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvolvedTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportmodel',
            name='techinvolved',
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='techinvolved',
            field=models.ManyToManyField(to='MetaApp.InvolvedTech'),
        ),
    ]
