# Generated by Django 3.2.6 on 2022-06-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0007_auto_20220620_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
