# Generated by Django 3.2.6 on 2022-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0008_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
