# Generated by Django 3.2.6 on 2022-06-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0009_alter_reportmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='cryptoamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
