# Generated by Django 3.2.6 on 2022-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0012_adminusermodel_realname'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='author',
            field=models.CharField(default='Superuser', max_length=200),
        ),
        migrations.AlterField(
            model_name='adminusermodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
