# Generated by Django 3.2.6 on 2022-06-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0013_auto_20220628_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
