# Generated by Django 3.2.6 on 2022-06-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0015_auto_20220629_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='relevantlocation',
            new_name='relevantlocations',
        ),
    ]
