# Generated by Django 3.2.6 on 2022-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0016_rename_relevantlocation_reportmodel_relevantlocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='target',
            field=models.CharField(choices=[('Individual', 'Individual'), ('School', 'School'), ('Public Building', 'Public Building'), ('Other', 'Other')], max_length=100),
        ),
    ]
