# Generated by Django 3.2.6 on 2022-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0017_alter_reportmodel_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='readabletech',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
