# Generated by Django 4.0.5 on 2022-07-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaApp', '0020_auto_20220705_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencemodel',
            name='evid',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='relevantlocationmodel',
            name='locid',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='target',
            field=models.CharField(choices=[('Individual', 'Individual'), ('School', 'School'), ('Public Building', 'Public Building'), ('Crypto Exchange', 'Crypto Exchange'), ('Online Gaming Platform', 'Online Gaming Platform'), ('Corporation', 'Corporation'), ('Online Forum', 'Online Forum'), ('Other', 'Other')], max_length=100),
        ),
    ]
